### ISSUE TITLE
Refactoring: sr2silo #01

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/sr2silo#62]
After this sprint until X-Mas some proper refactoring is necessary. Especially since we have decided that `sr2silo` will mostly be for `v-pipe`, not in general for imports of short reads to the silo. 

Let's restructure the product to have `sr2silo.vpipe.` functions ? 

Does any Object Orientation Make sense here ? 
 - perhaps organize an analysis as an object ?

Testing
- [x] #66
- [x] Add Unit-Tests for Functions
- [x] #72

Code Smells
- #60 

Restructuring
- [x] #61 
- [x] #79
- [x] #82
- [x] #74
- [x] #84

Other
- [x] Add Automatic Branch Deletion if PR done /  clean up old branches
- [x] #64
- [x] #83
- [x] #67
- [x] Close unused stashes - Deamon PR

**Comment by gordonkoehn** [comment]
A lot of progress was made, but this is secondary progress again.

**Comment by gordonkoehn** [comment]
Done. Making up a New Refactoring Quest. Closing this Epic Finnally.
